[workspace]
resolver = "2"
members = [
    "crates/cairo-coverage",
    "crates/cairo-coverage-core",
    "crates/cairo-coverage-test-utils",
]

[workspace.package]
version = "0.3.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.95"
assert_fs = "1.1.2"
camino = "1.1.9"
clap = { version = "4.5.23", features = ["derive"] }
cairo-annotations = "0.2.1"
cairo-lang-sierra = "2.9.2"
cairo-lang-sierra-to-casm = "2.9.2"
cairo-lang-starknet-classes = "2.9.2"
derived-deref = "2.1.0"
itertools = "0.13.0"
ignore = "0.4.23"
serde = "1.0.217"
serde_json = "1.0.134"
snapbox = "0.6.21"
indoc = "2.0.5"
regex = "1.11.1"
walkdir = "2.5.0"
