[workspace]
resolver = "2"
members = [
    "crates/cairo-coverage",
]

[workspace.package]
version = "0.3.0-rc0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.93"
assert_fs = "1.1.2"
camino = "1.1.9"
clap = { version = "4.5.21", features = ["derive"] }
cairo-annotations = "0.1.0"
cairo-lang-sierra = "2.8.2"
cairo-lang-sierra-to-casm = "2.8.2"
cairo-lang-starknet-classes = "2.8.2"
derived-deref = "2.1.0"
itertools = "0.13.0"
serde = "1.0.215"
serde_json = "1.0.133"
snapbox = "0.6.20"
indoc = "2.0.5"
regex = "1.11.1"
