[workspace]
resolver = "2"
members = [
    "crates/cairo-coverage",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.86"
camino = "1.1.7"
clap = { version = "4.5.13", features = ["derive"] }
cairo-lang-sierra = "2.7.0"
serde = "1.0.204"
serde_json = "1.0.122"
trace-data = { git = "https://github.com/software-mansion/cairo-profiler/", tag = "v0.5.0" }
